<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-7EUDCAL" failures="1" tests="3" name="SAUCE TESTS" time="11.136" errors="0" timestamp="2023-05-30T21:28:52 GMT-04:00">
  <testcase classname="SauceTestSuite.LogOutTest" name="logout" time="5.185"/>
  <testcase classname="SauceTestSuite.LoginTest" name="InvalidLogin" time="2.854">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at SauceTestSuite.LoginTest.InvalidLogin(LoginTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- InvalidLogin -->
  <testcase classname="SauceTestSuite.LoginTest" name="validLogin" time="3.017"/>
</testsuite> <!-- SAUCE TESTS -->
